Elga/PL/Controllers/CategoryController.cs
using FashionApp.BLL.DTO.Requests;
using FashionApp.BLL.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
	{
		public ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
			_categoryService = categoryService;
        }
        // GET: CategoryController
        public ActionResult Index()
		{
			return View();
		}

		// GET: CategoryController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: CategoryController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: CategoryController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(CategoryAddModel model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var res = _categoryService.AddCategory(model);
					if(res.Status == FashionApp.BLL.DTO.ViewResponseStatus.OK)
					{
						return RedirectToAction("Index", "Product");
					}
				}
			}
			catch
			{
				return View(model);
			}
			return View(model);
		}

		// GET: CategoryController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: CategoryController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: CategoryController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: CategoryController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

Elga/PL/Controllers/FavouriteController.cs
using System.Security.Claims;
using FashionApp.BLL.DTO;
using FashionApp.BLL.Services;
using FashionApp.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    [Authorize(Roles = "User")]
    public class FavouriteController : Controller
    {
        public IFavouritesService _favouriteService;
        public IProductService _productService;
        private readonly UserManager<AppUser> _userManager;

        public FavouriteController(IFavouritesService favouritesService, IProductService productService, UserManager<AppUser> userManager)
        {
            _favouriteService = favouritesService;
            _productService = productService;
            _userManager = userManager;
        }
        public int GetCurrentUserId()
        {
            int.TryParse(((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.NameIdentifier).Value, out int userId);
            return userId;
        }
        // GET: FavouriteController
        public ActionResult Index()
        {
            var userId = GetCurrentUserId(); ;
            return View(_favouriteService.GetAllFavourites(userId));//merr listen e favourites per userin e loguar
        }

        // GET: FavouriteController/Create

        public JsonResult Create(int id)
        {
            var userId = GetCurrentUserId();
            var userFavourites = _favouriteService.GetAllFavourites(userId);//merr favourites te userit aktual te loguar
            if (userFavourites.FirstOrDefault(x => x.ProductId == id) != null)
            {
                _favouriteService.DeleteFavourite(id, userId);
                return Json(new Dictionary<string, string>()
                {
                    {"status", "completed" },
                    {"message", "deleted" }
                });
            }
            var addedFavourite = new FashionApp.BLL.DTO.Favourite()
            {
                ProductId = id,
                UserId = userId
            };
            if (_favouriteService.AddFavourite(addedFavourite).Status == ViewResponseStatus.OK)
            {
                return Json(new Dictionary<string, string>()
                {
                    {"status", "completed" },
                    {"message", "added" }
                });
            }
            return Json(new Dictionary<string, string>()
                {
                    {"status", "failed" },
                    {"message", "Action could not be completed" }
                });
        }

        // GET: FavouriteController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var userId = GetCurrentUserId();
                if (_favouriteService.DeleteFavourite(id, userId).Status == ViewResponseStatus.OK)
                {
                    return Json(new Dictionary<string, string>()//shkon si response te view/index i favourites
                    {
                        {"status", "completed" }
                    });
                }
            }
            catch (Exception){}
            return Json(new Dictionary<string, string>()
            {
                {"status", "failed" }
            });

        }
    }
}

Elga/PL/Controllers/ProductController.cs
using FashionApp.BLL.DTO.Requests;
using FashionApp.BLL.DTO.Responses;
using FashionApp.BLL.Services;
using FashionApp.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FashionApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productsService;
        private readonly ICategoryService _categoryService;
        private readonly IWebHostEnvironment webHostEnvironment;
        //**************************
        public ProductController(IProductService productsService, ICategoryService categoryService, IWebHostEnvironment hostEnvironment)//DI - injects IProductService interface to ProductController
        {
            _productsService = productsService;
            _categoryService = categoryService;
            webHostEnvironment = hostEnvironment;
        }
        // GET: ProductController
        public async Task<IActionResult> Index(int categories, string search)
        {
            var products = await _productsService.Filter(categories, search);
			ViewBag.Categories = await _categoryService.GetAllCategories();
            return View(products);
        }

        // GET: ProductController/Details/5
        public ActionResult Details(int id)
        {
            return View(_productsService.GetById(id));
        }

        // GET: ProductController/Add
        [HttpGet]
        [Authorize(Roles = "Admin, Staff")]
        public async Task<IActionResult> Add()
        {
            ViewBag.Categories = await _categoryService.GetAllCategories();
            return View();
        }

        [HttpPost]
		[Authorize(Roles = "Admin,Staff")]
		public IActionResult Add(BLL.DTO.Requests.ProductAddModel model)
        {
            if (ModelState.IsValid)
            {
                model.ImagePath = UploadedFile(model);
                var res = _productsService.AddProduct(model);
                if(res.Status == BLL.DTO.ViewResponseStatus.OK)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        // GET: ProductController/Edit/5
        [HttpGet]
		[Authorize(Roles = "Admin,Staff")]
		public async Task<IActionResult> Edit(int id)
        {
            var existingById = _productsService.GetById(id);
            ViewBag.Categories = await _categoryService.GetAllCategories();
            if (existingById != null)
            {
                return View(new ProductAddModel
                {
                    Title = existingById.Title,
                    Description = existingById.Description, 
                    Price = existingById.Price,
                    CategoryId = existingById.CategoryId,
                    Quantity = existingById.Quantity,
                    ImagePath = existingById.ImagePath
                });
            }
			return RedirectToAction(nameof(Index));
		}

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin,Staff")]
		public ActionResult Edit(int id, ProductAddModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var res = _productsService.EditProduct(id, model);
			if (res.Status == BLL.DTO.ViewResponseStatus.OK)
            {
				return RedirectToAction("Index");
			}
            return View(model);
		}

        // GET: ProductController/Delete/5
        [HttpGet]
		[Authorize(Roles = "Admin")]
		public ActionResult Delete(int id)
        {
            var existingById = _productsService.GetById(id);
            if (existingById != null)
            {
                return View(_productsService.GetById(id));
            }
            return RedirectToAction("Index");
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public ActionResult Delete(int id, ProductAddModel model)
        {
            try
            {
                var product = _productsService.DeleteProduct(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        [Authorize(Roles = "Admin, Staff")]
        private string UploadedFile(ProductAddModel model)
        {
            string uniqueFileName = null;
            try
            {
                if (model.Image != null)
                {
                    string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Image.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        model.Image.CopyTo(fileStream);
                    }
                }
            }
            catch (Exception) { }

            return uniqueFileName;
        }
    }
}

Elga/PL/Views/Product/Add.cshtml
@using FashionApp.BLL.DTO.Responses;
@model FashionApp.BLL.DTO.Requests.ProductAddModel

@{
    ViewData["Title"] = "Add";
    var categories = ViewBag.Categories as List<CategoryIndexModel>;
}

<h1>Add Products</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                @Html.DropDownListFor(x => Model.CategoryId, new SelectList(categories, "Id", "Name"), htmlAttributes: new { @class = "form-control"})
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <div class="custom-file">
                        <input asp-for="Image" class="custom-file-input" id="customFile" onchange="ImgPre(this)">
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div style="height: 100px; width: 100px;margin-bottom: 2rem">
                    <img id="ImgPreview" style="object-fit: contain;" style="width: 100%" />
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    function ImgPre(input) {
        if (input.files[0]) {
            var uploadimg = new FileReader();
            uploadimg.onload = function (displayimg) {
                $("#ImgPreview").attr('src', displayimg.target.result);
            }
            uploadimg.readAsDataURL(input.files[0]);
        }
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Elga/PL/Views/Product/Delete.cshtml
@model FashionApp.BLL.DTO.Responses.ProductDetailsModel

@{
    ViewData["Title"] = "Delete";
}

<h1>
    Delete @Html.DisplayFor(model => model.Title)
</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" style="color: black;">Back to List</a>
    </form>
</div>

Elga/PL/Views/Product/Details.cshtml
@using System.Web;
@model FashionApp.BLL.DTO.Responses.ProductDetailsModel;
@{
	ViewData["Title"] = "Details";
}

<div class="content">
	<div class="container">
		<div class="image" style="background-image: url(@Url.Content("~/images/" + @Model.ImagePath))"></div>
		<div class="details">
			<h1>@Html.DisplayFor(model => model.Title)</h1>
			<p>@Html.DisplayFor(model => model.Description)</p>
			<div class="price">@Html.DisplayFor(model => model.Price) EUR</div>
			<div class="btns">
				<a href="#" style="color: white; text-shadow: 0 0 3px red" id="favourites-btn"><i class="fa-solid fa-heart"></i>Add to Favourites</a>
				<a href="#" style="color: white; text-shadow: 0 0 3px blue" id="cart-btn"><i class="fa-solid fa-cart-shopping"></i>Add to Cart</a>
			</div>
		</div>
	</div>
</div>





<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
	$(document).ready(function () {
		$("#favourites-btn").on("click", function () {
			debugger;
			$.ajax({
				type: 'GET',
				url: '@Url.Action("Create", "Favourite")?id=' + @Model.Id,
				dataType: 'json',
				success: function (response) {
					debugger;
					if (response.status === "completed" && response.message === "added") {
						$("#favourites-btn").css("color", "red");
					}
					else if (response.status === "completed" && response.message === "deleted") {
						$("#favourites-btn").css({
							"color": "white",
							"text-shadow": "0 0 3px red"
						});
					}

				},
				error: function (response) {
					debugger;
				},
			});
		});
		$("#cart-btn").on("click", function () {
			debugger;
			$.ajax({
				type: 'GET',
				url: '@Url.Action("Create", "Cart")?id=' + @Model.Id,
				dataType: 'json',
				success: function (response) {
					debugger;
					if (response.status === "completed" && response.message === "added") {
						$("#cart-btn").css("color", "blue");
					}
					else if (response.status === "completed" && response.message === "deleted") {
						$("#cart-btn").css({
							"color": "white",
							"text-shadow": "0 0 3px red"
						});
					}

				},
				error: function (response) {
					debugger;
				},
			});
		});

	});
</script>

Elga/PL/Views/Product/Edit.cshtml
@using FashionApp.BLL.DTO.Responses;
@model FashionApp.BLL.DTO.Requests.ProductAddModel

@{
	ViewData["Title"] = "Edit";
	var categories = ViewBag.Categories as List<CategoryIndexModel>;
}

<h1>Edit</h1>

<h4>Edit Product</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Price" class="control-label"></label>
				<input asp-for="Price" class="form-control" />
				<span asp-validation-for="Price" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="CategoryId" class="control-label"></label>
				@Html.DropDownListFor(x => x.CategoryId,
					new SelectList(categories, "Id", "Name", Model.CategoryId),
					new { @class = "form-control" })    
				<span asp-validation-for="CategoryId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Elga/PL/Views/Product/Index.cshtml
@using FashionApp.BLL.DTO.Responses;
@model IEnumerable<FashionApp.BLL.DTO.Responses.ProductIndexModel>

@{
	ViewData["Title"] = "Index";
	var categories = ViewBag.Categories as List<CategoryIndexModel>;
}


@if (User.IsInRole("Admin"))
{
	<style>
		.search-form {
		display: grid;
		grid-template-columns: 0.2fr 1fr 4fr 1fr;
		gap: 2rem;
		margin-bottom: 2rem;
		}
	</style>
}
else
{
	<style>
		.search-form {
		display: grid;
		grid-template-columns: 1fr 4fr 1fr;
		gap: 2rem;
		margin-bottom: 2rem;
		}
	</style>
}

<div style="margin-bottom: 2rem;;display: flex; align-items: center">
	<span class="h1">Products</span>

	@if (User.IsInRole("Admin") || User.IsInRole("Staff"))
	{
		<a asp-action="Add" class="btn btn-primary" style="margin-left: 2rem;">Add Product</a>
	}
</div>


<form asp-action="Index" class="search-form">
	@if (!User.IsInRole("User"))
	{
		@if (User.IsInRole("Admin"))
		{
			@Html.ActionLink("+", "Create", "Category", new{}, new{@class="btn btn-primary"})
		}
	}
	@Html.DropDownListFor(x => categories, new SelectList(categories, "Id", "Name"), "Select a category", htmlAttributes: new { @class = "form-control"})
	<input type="text" class="form-control" name="search" />
	<input type="submit" class="btn btn-secondary" value="Submit" />
</form>

<div class="products">
	@foreach (var item in Model)
	{
		<div class="card" style="width: 18rem;">
			<img class="card-img-top" src="~/images/@item.ImagePath" alt="Card image cap">
			<div class="card-body">
				<h5 class="card-title"> @Html.DisplayFor(modelItem => item.Title) </h5>
				<p>@Html.DisplayFor(modelItem => item.Price) EUR</p>

				@if (!User.Identity.IsAuthenticated)
				{
					@Html.ActionLink("See more", "Details", new { id=item.Id  }, new{@class="btn btn-primary"})
				}

				@if (User.IsInRole("User"))
				{
					@Html.ActionLink("See more", "Details", new { id=item.Id  }, new{@class="btn btn-primary"})
				}
				@if (!User.IsInRole("User") & (User.Identity.IsAuthenticated))
				{
					@Html.ActionLink("Edit", "Edit", new { id=item.Id  }, new{@class="btn btn-primary"})
					@if (User.IsInRole("Admin"))
					{
						@Html.ActionLink("Delete", "Delete", new { id=item.Id  }, new{@class="btn btn-danger", style="margin-left: 1rem"})
					}

				}

			</div>
		</div>
	}
</div>