Elga/PL/Controllers/FavouriteController.cs
using System.Security.Claims;
using FashionApp.BLL.DTO;
using FashionApp.BLL.Services;
using FashionApp.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    [Authorize(Roles = "User")]
    public class FavouriteController : Controller
    {
        public IFavouritesService _favouriteService;
        public IProductService _productService;
        private readonly UserManager<AppUser> _userManager;

        public FavouriteController(IFavouritesService favouritesService, IProductService productService, UserManager<AppUser> userManager)
        {
            _favouriteService = favouritesService;
            _productService = productService;
            _userManager = userManager;
        }
        public int GetCurrentUserId()
        {
            int.TryParse(((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.NameIdentifier).Value, out int userId);
            return userId;
        }
        // GET: FavouriteController
        public ActionResult Index()
        {
            var userId = GetCurrentUserId(); ;
            return View(_favouriteService.GetAllFavourites(userId));//merr listen e favourites per userin e loguar
        }

        // GET: FavouriteController/Create

        public JsonResult Create(int id)
        {
            var userId = GetCurrentUserId();
            var userFavourites = _favouriteService.GetAllFavourites(userId);//merr favourites te userit aktual te loguar
            if (userFavourites.FirstOrDefault(x => x.ProductId == id) != null)
            {
                _favouriteService.DeleteFavourite(id, userId);
                return Json(new Dictionary<string, string>()
                {
                    {"status", "completed" },
                    {"message", "deleted" }
                });
            }
            var addedFavourite = new FashionApp.BLL.DTO.Favourite()
            {
                ProductId = id,
                UserId = userId
            };
            if (_favouriteService.AddFavourite(addedFavourite).Status == ViewResponseStatus.OK)
            {
                return Json(new Dictionary<string, string>()
                {
                    {"status", "completed" },
                    {"message", "added" }
                });
            }
            return Json(new Dictionary<string, string>()
                {
                    {"status", "failed" },
                    {"message", "Action could not be completed" }
                });
        }

        // GET: FavouriteController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var userId = GetCurrentUserId();
                if (_favouriteService.DeleteFavourite(id, userId).Status == ViewResponseStatus.OK)
                {
                    return Json(new Dictionary<string, string>()//shkon si response te view/index i favourites
                    {
                        {"status", "completed" }
                    });
                }
            }
            catch (Exception){}
            return Json(new Dictionary<string, string>()
            {
                {"status", "failed" }
            });

        }
    }
}

Elga/PL/Controllers/OrderController.cs
using System.Security.Claims;
using FashionApp.BLL.Services;
using FashionApp.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    [Authorize(Roles = "Admin,User")]

    public class OrderController : Controller
    {
        public IOrderService _orderService;
        private readonly UserManager<AppUser> _userManager;
        public OrderController(IOrderService orderService, UserManager<AppUser> userManager)
        {
            _orderService = orderService;
            _userManager = userManager;
        }
        public int GetCurrentUserId()
        {
            int.TryParse(((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.NameIdentifier).Value, out int userId);
            return userId;
        }
        // GET: OrderController
        public ActionResult Index()
        {
           
            var orders = new List<Order>();
            if(User.IsInRole("Admin"))
            {
                orders = _orderService.GetAllOrders();
            }
            else
            {
                var userId = GetCurrentUserId();
                orders = _orderService.GetAllOrdersByUserId(userId);
            }
            return View(orders);
        }
    }
}

Elga/PL/Controllers/ProductController.cs
using FashionApp.BLL.DTO.Requests;
using FashionApp.BLL.DTO.Responses;
using FashionApp.BLL.Services;
using FashionApp.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FashionApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productsService;
        private readonly ICategoryService _categoryService;
        private readonly IWebHostEnvironment webHostEnvironment;
        //**************************
        public ProductController(IProductService productsService, ICategoryService categoryService, IWebHostEnvironment hostEnvironment)//DI - injects IProductService interface to ProductController
        {
            _productsService = productsService;
            _categoryService = categoryService;
            webHostEnvironment = hostEnvironment;
        }
        // GET: ProductController
        public async Task<IActionResult> Index(int categories, string search)
        {
            var products = await _productsService.Filter(categories, search);
			ViewBag.Categories = await _categoryService.GetAllCategories();
            return View(products);
        }

        // GET: ProductController/Details/5
        public ActionResult Details(int id)
        {
            return View(_productsService.GetById(id));
        }

        // GET: ProductController/Add
        [HttpGet]
        [Authorize(Roles = "Admin, Staff")]
        public async Task<IActionResult> Add()
        {
            ViewBag.Categories = await _categoryService.GetAllCategories();
            return View();
        }

        [HttpPost]
		[Authorize(Roles = "Admin,Staff")]
		public IActionResult Add(BLL.DTO.Requests.ProductAddModel model)
        {
            if (ModelState.IsValid)
            {
                model.ImagePath = UploadedFile(model);
                var res = _productsService.AddProduct(model);
                if(res.Status == BLL.DTO.ViewResponseStatus.OK)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        // GET: ProductController/Edit/5
        [HttpGet]
		[Authorize(Roles = "Admin,Staff")]
		public async Task<IActionResult> Edit(int id)
        {
            var existingById = _productsService.GetById(id);
            ViewBag.Categories = await _categoryService.GetAllCategories();
            if (existingById != null)
            {
                return View(new ProductAddModel
                {
                    Title = existingById.Title,
                    Description = existingById.Description, 
                    Price = existingById.Price,
                    CategoryId = existingById.CategoryId,
                    Quantity = existingById.Quantity,
                    ImagePath = existingById.ImagePath
                });
            }
			return RedirectToAction(nameof(Index));
		}

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin,Staff")]
		public ActionResult Edit(int id, ProductAddModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var res = _productsService.EditProduct(id, model);
			if (res.Status == BLL.DTO.ViewResponseStatus.OK)
            {
				return RedirectToAction("Index");
			}
            return View(model);
		}

        // GET: ProductController/Delete/5
        [HttpGet]
		[Authorize(Roles = "Admin")]
		public ActionResult Delete(int id)
        {
            var existingById = _productsService.GetById(id);
            if (existingById != null)
            {
                return View(_productsService.GetById(id));
            }
            return RedirectToAction("Index");
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public ActionResult Delete(int id, ProductAddModel model)
        {
            try
            {
                var product = _productsService.DeleteProduct(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        [Authorize(Roles = "Admin, Staff")]
        private string UploadedFile(ProductAddModel model)
        {
            string uniqueFileName = null;
            try
            {
                if (model.Image != null)
                {
                    string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Image.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        model.Image.CopyTo(fileStream);
                    }
                }
            }
            catch (Exception) { }

            return uniqueFileName;
        }
    }
}

Elga/PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Chéri</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/product.css" asp-append-version="true" />
	@*    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
	*@
	<link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				@*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Chéri</a>*@
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index" style="color: #c30434;font-size:1.2rem">Chéri</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
						</li>
						@if (User.Identity.IsAuthenticated)
						{
							@if (User.IsInRole("User"))
							{
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Favourite" asp-action="Index"><i class="fa-solid fa-heart" style="color: #c30434;"></i></a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index"><i class="fa-solid fa-cart-shopping" style="color: #511f2b;"></i></a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index"><i class="fa-solid fa-boxes-stacked" style="color: #511f2b;"></i></a>
								</li>
							}
							@if (User.IsInRole("Admin"))
							{
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index"><i class="fa-solid fa-boxes-stacked" style="color: #511f2b;"></i></a>
								</li>
							}
						}


					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		@RenderBody()
	</div>
	<footer class="border-top footer text-muted">
		<div class="container">
			&copy;ALL RIGHTS RESERVED - Chéri
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>